let main = document.createElement('main');
main.className = 'mainClass check item';
document.body.appendChild(main);
let div = document.createElement('div');
div.id = 'myDiv';
main.appendChild(div);
let p = document.createElement('p');
div.appendChild(p);
let pText = document.createTextNode('First paragraph');
p.appendChild(pText);